//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight_backend.Models
{
    using System;
    using System.Collections.Generic;
    using Flight_backend.Repository;
    using Flight_backend.Models;
    using Flight_backend.Controllers;
    
    public partial class User
    {
        public string Username { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
    }
}
